spring.application.name=vulnerable-spring-boot
spring.datasource.url=jdbc:h2:mem:vulnerabledb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.h2.console.enabled=true
spring.h2.console.settings.web-allow-others=true
server.error.include-stacktrace=always
logging.level.com.example.vulnerableapp=DEBUG
